spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-shuiyun-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-shuiyun-test
#保存的时候需要保存为uat-8